package com.hudongwx.studentSys.model.testModel;

import com.hudongwx.studentSys.common.testBaseModel.BaseQuestionsQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionsQuestionnaire extends BaseQuestionsQuestionnaire<QuestionsQuestionnaire> {
	public static final QuestionsQuestionnaire dao = new QuestionsQuestionnaire();
}
