package com.hudongwx.studentSys.model.testModel;

import com.hudongwx.studentSys.common.testBaseModel.BaseQuestions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questions extends BaseQuestions<Questions> {
	public static final Questions dao = new Questions();
}
