package com.hudongwx.studentSys.model.testModel;

import com.hudongwx.studentSys.common.testBaseModel.BaseQuestionBigType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionBigType extends BaseQuestionBigType<QuestionBigType> {
	public static final QuestionBigType dao = new QuestionBigType();
}
