package com.hudongwx.studentSys.model.testModel;

import com.hudongwx.studentSys.common.testBaseModel.BaseQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questionnaire extends BaseQuestionnaire<Questionnaire> {
	public static final Questionnaire dao = new Questionnaire();
}
