package com.hudongwx.studentSys.model.testModel;

import com.hudongwx.studentSys.common.testBaseModel.BaseQuestionnaireResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionnaireResult extends BaseQuestionnaireResult<QuestionnaireResult> {
	public static final QuestionnaireResult dao = new QuestionnaireResult();
}
