package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCertificate<M extends BaseCertificate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStudentId(java.lang.Integer studentId) {
		set("studentId", studentId);
	}

	public java.lang.Integer getStudentId() {
		return get("studentId");
	}

	public void setEnrollTime(java.lang.Long enrollTime) {
		set("enrollTime", enrollTime);
	}

	public java.lang.Long getEnrollTime() {
		return get("enrollTime");
	}

	public void setEndTime(java.lang.Long endTime) {
		set("endTime", endTime);
	}

	public java.lang.Long getEndTime() {
		return get("endTime");
	}

	public void setAddTime(java.lang.Long addTime) {
		set("addTime", addTime);
	}

	public java.lang.Long getAddTime() {
		return get("addTime");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

}
