package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubsidyApplicationSum<M extends BaseSubsidyApplicationSum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setApplicantId(java.lang.Integer applicantId) {
		set("applicantId", applicantId);
	}

	public java.lang.Integer getApplicantId() {
		return get("applicantId");
	}

	public void setApproverId(java.lang.Integer approverId) {
		set("approverId", approverId);
	}

	public java.lang.Integer getApproverId() {
		return get("approverId");
	}

	public void setTotalSubsidy(java.lang.Integer totalSubsidy) {
		set("totalSubsidy", totalSubsidy);
	}

	public java.lang.Integer getTotalSubsidy() {
		return get("totalSubsidy");
	}

	public void setTotalBonus(java.lang.Integer totalBonus) {
		set("totalBonus", totalBonus);
	}

	public java.lang.Integer getTotalBonus() {
		return get("totalBonus");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setClassIdGather(java.lang.String classIdGather) {
		set("classIdGather", classIdGather);
	}

	public java.lang.String getClassIdGather() {
		return get("classIdGather");
	}

	public void setApplicationDate(java.lang.Long applicationDate) {
		set("applicationDate", applicationDate);
	}

	public java.lang.Long getApplicationDate() {
		return get("applicationDate");
	}

	public void setApproveStatus(java.lang.Integer approveStatus) {
		set("approveStatus", approveStatus);
	}

	public java.lang.Integer getApproveStatus() {
		return get("approveStatus");
	}

}
