package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestQuestionnaireClass<M extends BaseTestQuestionnaireClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}

	public java.lang.Integer getClassId() {
		return get("classId");
	}

	public void setTestQuestionnaireId(java.lang.Integer testQuestionnaireId) {
		set("testQuestionnaireId", testQuestionnaireId);
	}

	public java.lang.Integer getTestQuestionnaireId() {
		return get("testQuestionnaireId");
	}

	public void setTestQuestionnaireStartTime(java.lang.Long testQuestionnaireStartTime) {
		set("testQuestionnaireStartTime", testQuestionnaireStartTime);
	}

	public java.lang.Long getTestQuestionnaireStartTime() {
		return get("testQuestionnaireStartTime");
	}

	public void setTestQuestionnaireEndTime(java.lang.Long testQuestionnaireEndTime) {
		set("testQuestionnaireEndTime", testQuestionnaireEndTime);
	}

	public java.lang.Long getTestQuestionnaireEndTime() {
		return get("testQuestionnaireEndTime");
	}

}
