package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestTag<M extends BaseTestTag<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTagName(java.lang.String tagName) {
		set("tagName", tagName);
	}

	public java.lang.String getTagName() {
		return get("tagName");
	}

	public void setQuestionCnt(java.lang.Integer questionCnt) {
		set("questionCnt", questionCnt);
	}

	public java.lang.Integer getQuestionCnt() {
		return get("questionCnt");
	}

}
