package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDomain<M extends BaseDomain<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDomainTitle(java.lang.String domainTitle) {
		set("domainTitle", domainTitle);
	}

	public java.lang.String getDomainTitle() {
		return get("domainTitle");
	}

	public void setDomainMessage(java.lang.String domainMessage) {
		set("domainMessage", domainMessage);
	}

	public java.lang.String getDomainMessage() {
		return get("domainMessage");
	}

	public void setDomainOperaterId(java.lang.Integer domainOperaterId) {
		set("domainOperaterId", domainOperaterId);
	}

	public java.lang.Integer getDomainOperaterId() {
		return get("domainOperaterId");
	}

	public void setDomainCreateTime(java.lang.Long domainCreateTime) {
		set("domainCreateTime", domainCreateTime);
	}

	public java.lang.Long getDomainCreateTime() {
		return get("domainCreateTime");
	}

	public void setDomainUpdateTime(java.lang.Long domainUpdateTime) {
		set("domainUpdateTime", domainUpdateTime);
	}

	public java.lang.Long getDomainUpdateTime() {
		return get("domainUpdateTime");
	}

}
