package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudentTrackInfo<M extends BaseStudentTrackInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTargetId(java.lang.Integer targetId) {
		set("targetId", targetId);
	}

	public java.lang.Integer getTargetId() {
		return get("targetId");
	}

	public void setTargetName(java.lang.String targetName) {
		set("targetName", targetName);
	}

	public java.lang.String getTargetName() {
		return get("targetName");
	}

	public void setInformation(java.lang.String information) {
		set("information", information);
	}

	public java.lang.String getInformation() {
		return get("information");
	}

	public void setTrackTime(java.lang.Long trackTime) {
		set("trackTime", trackTime);
	}

	public java.lang.Long getTrackTime() {
		return get("trackTime");
	}

	public void setOperaterId(java.lang.Integer operaterId) {
		set("operaterId", operaterId);
	}

	public java.lang.Integer getOperaterId() {
		return get("operaterId");
	}

	public void setOperater(java.lang.String operater) {
		set("operater", operater);
	}

	public java.lang.String getOperater() {
		return get("operater");
	}

}
