package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatus<M extends BaseStatus<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStatusName(java.lang.String statusName) {
		set("statusName", statusName);
	}

	public java.lang.String getStatusName() {
		return get("statusName");
	}

	public void setField(java.lang.String field) {
		set("field", field);
	}

	public java.lang.String getField() {
		return get("field");
	}

	public void setMark(java.lang.String mark) {
		set("mark", mark);
	}

	public java.lang.String getMark() {
		return get("mark");
	}

}
