package com.hudongwx.studentSys.common.testBaseModel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionnaireResult<M extends BaseQuestionnaireResult<M>> extends Model<M> implements IBean {

	public void setIdUser(java.lang.Integer idUser) {
		set("id_user", idUser);
	}

	public java.lang.Integer getIdUser() {
		return get("id_user");
	}

	public void setIdQuestionnaire(java.lang.Integer idQuestionnaire) {
		set("id_questionnaire", idQuestionnaire);
	}

	public java.lang.Integer getIdQuestionnaire() {
		return get("id_questionnaire");
	}

	public void setQuestionsReply(java.lang.String questionsReply) {
		set("questions_reply", questionsReply);
	}

	public java.lang.String getQuestionsReply() {
		return get("questions_reply");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

}
