package com.hudongwx.testing.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionsTag<M extends BaseTQuestionsTag<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setIsEnable(Integer isEnable) {
		set("is_enable", isEnable);
	}

	public Integer getIsEnable() {
		return get("is_enable");
	}

}
