package com.hudongwx.testing.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestions<M extends BaseTQuestions<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setBigTypeId(Integer bigTypeId) {
		set("big_type_id", bigTypeId);
	}

	public Integer getBigTypeId() {
		return get("big_type_id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setTagId(String tagId) {
		set("tag_id", tagId);
	}

	public String getTagId() {
		return get("tag_id");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setScore(Integer score) {
		set("score", score);
	}

	public Integer getScore() {
		return get("score");
	}

	public void setAnswer(String answer) {
		set("answer", answer);
	}

	public String getAnswer() {
		return get("answer");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}

	public String getCreateTime() {
		return get("create_time");
	}

	public void setCreaterId(Integer createrId) {
		set("creater_id", createrId);
	}

	public Integer getCreaterId() {
		return get("creater_id");
	}

	public void setIsEnable(Integer isEnable) {
		set("is_enable", isEnable);
	}

	public Integer getIsEnable() {
		return get("is_enable");
	}

}
