package com.hudongwx.testing.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionsQuestionnaire<M extends BaseTQuestionsQuestionnaire<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setIdQuestionnaire(Integer idQuestionnaire) {
		set("id_questionnaire", idQuestionnaire);
	}

	public Integer getIdQuestionnaire() {
		return get("id_questionnaire");
	}

	public void setIdQuestions(Integer idQuestions) {
		set("id_questions", idQuestions);
	}

	public Integer getIdQuestions() {
		return get("id_questions");
	}

}
