package com.hudongwx.testing.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionnaire<M extends BaseTQuestionnaire<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setClassId(Integer classId) {
		set("class_id", classId);
	}

	public Integer getClassId() {
		return get("class_id");
	}

	public void setStartTime(String startTime) {
		set("start_time", startTime);
	}

	public String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(String endTime) {
		set("end_time", endTime);
	}

	public String getEndTime() {
		return get("end_time");
	}

	public void setCreatTime(String creatTime) {
		set("creat_time", creatTime);
	}

	public String getCreatTime() {
		return get("creat_time");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setTotalScore(Integer totalScore) {
		set("total_score", totalScore);
	}

	public Integer getTotalScore() {
		return get("total_score");
	}

	public void setNote(String note) {
		set("note", note);
	}

	public String getNote() {
		return get("note");
	}

	public void setJoinNumber(Integer joinNumber) {
		set("join_number", joinNumber);
	}

	public Integer getJoinNumber() {
		return get("join_number");
	}

	public void setSubmitNumer(Integer submitNumer) {
		set("submit_numer", submitNumer);
	}

	public Integer getSubmitNumer() {
		return get("submit_numer");
	}

	public void setAverScore(Integer averScore) {
		set("aver_score", averScore);
	}

	public Integer getAverScore() {
		return get("aver_score");
	}

}
