package com.hudongwx.testing.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionnaireResult<M extends BaseTQuestionnaireResult<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setIdUser(Integer idUser) {
		set("id_user", idUser);
	}

	public Integer getIdUser() {
		return get("id_user");
	}

	public void setIdQuestionnaire(Integer idQuestionnaire) {
		set("id_questionnaire", idQuestionnaire);
	}

	public Integer getIdQuestionnaire() {
		return get("id_questionnaire");
	}

	public void setQuestionsReply(String questionsReply) {
		set("questions_reply", questionsReply);
	}

	public String getQuestionsReply() {
		return get("questions_reply");
	}

}
