package com.hudongwx.studentsys.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("stumanager_attendance", "id", Attendance.class);
		arp.addMapping("stumanager_certificate", "id", Certificate.class);
		arp.addMapping("stumanager_class", "id", Class.class);
		arp.addMapping("stumanager_domain", "id", Domain.class);
		arp.addMapping("stumanager_domain_tag", "id", DomainTag.class);
		arp.addMapping("stumanager_employee", "id", Employee.class);
		arp.addMapping("stumanager_mapping", "id", Mapping.class);
		arp.addMapping("stumanager_obtain_employment", "id", ObtainEmployment.class);
		arp.addMapping("stumanager_region", "regionId", Region.class);
		arp.addMapping("stumanager_repayment", "id", Repayment.class);
		arp.addMapping("stumanager_repayment_type", "id", RepaymentType.class);
		arp.addMapping("stumanager_role", "id", Role.class);
		arp.addMapping("stumanager_student", "id", Student.class);
		arp.addMapping("stumanager_subsidy_application", "id", SubsidyApplication.class);
		arp.addMapping("stumanager_subsidy_classinfo", "id", SubsidyClassinfo.class);
		arp.addMapping("stumanager_test_question", "id", TestQuestion.class);
		arp.addMapping("stumanager_test_questionnaire", "id", TestQuestionnaire.class);
		arp.addMapping("stumanager_test_questionnaire_class", "id", TestQuestionnaireClass.class);
		arp.addMapping("stumanager_test_questionnaire_question", "id", TestQuestionnaireQuestion.class);
		arp.addMapping("stumanager_test_reply", "id", TestReply.class);
		arp.addMapping("stumanager_test_tag", "id", TestTag.class);
		arp.addMapping("stumanager_test_tag_question", "id", TestTagQuestion.class);
		arp.addMapping("stumanager_test_type", "id", TestType.class);
		arp.addMapping("stumanager_training_project", "id", TrainingProject.class);
		arp.addMapping("stumanager_user", "id", User.class);
		arp.addMapping("stumanager_user_region", "", UserRegion.class);
	}
}

