package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseAttendance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attendance extends BaseAttendance<Attendance> {
	public static final Attendance dao = new Attendance();
	public static final String SQL_FROM = " from stumanager_attendance ";
}
