package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();
	public static final String SEARCH_FROM_CLASS = "select * from stumanager_class ";
	public static final String SQL_FROM = " from stumanager_class ";
}
