package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseObtainemployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Obtainemployment extends BaseObtainemployment<Obtainemployment> {
	public static final Obtainemployment dao = new Obtainemployment();
}
