package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseObtainEmployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ObtainEmployment extends BaseObtainEmployment<ObtainEmployment> {
	public static final ObtainEmployment dao = new ObtainEmployment();
}
