package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
    public static final Region dao = new Region();
    public static final String FROM_REGION = " from stumanager_region ";
    public static final String SEARCH_FROM_REGION = "select * from stumanager_region ";
}
