package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region();
}
