package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRepaymentType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RepaymentType extends BaseRepaymentType<RepaymentType> {
	public static final RepaymentType dao = new RepaymentType();
	public static final String SEARCH_FROM_REPAYMENT_TYPE = "select * from stumanager_repayment_type ";
}
