package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRepayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Repayment extends BaseRepayment<Repayment> {
	public static final Repayment dao = new Repayment();
	public static final String SQL_FROM = " from stumanager_repayment ";
}
