package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRoleRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRegion extends BaseRoleRegion<RoleRegion> {
	public static final RoleRegion dao = new RoleRegion();
	public static final String SELECT_FROM_ROLEREGION="select * from stumanager_role_region ";
}
