package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRoleRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRegion extends BaseRoleRegion<RoleRegion> {
	public static final RoleRegion dao = new RoleRegion();
}
