package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseStudent;

import java.util.Objects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
    public static final int STATUS_STUDYING = 1;//在读
    public static final int STATUS_PAUSE = 2;//休学
    public static final int STATUS_DROPPED = 14;//退学
    public static final int STATUS_REFUND = 15;//退费
    public static final int STATUS_REPEAT = 3;//重修
    public static final int STATUS_GRADUATION = 4;//毕业
    public static final int STATUS_OUT_OF_CONTACT = 5;//失联
    public static final int STATUS_GRADUATION_OUT_OF_CONTACT = 700;//毕业后失联
    public static final int EMPLOYMENTSTATUS_EMPLOYED = 6;//已就业
    public static final int EMPLOYMENTSTATUS_UN_EMPLOYED = 7;//未就业
    public static final int EMPLOYMENTSTATUS_IN_APPROVAL = 18;//就业审核中
    public static final int STATUS_CHECKED = 11;//选中
    public static final int STATUS_UN_CHECKED = 12;//未选中
    private StudentEmployment studentEmployment;
    private Class classModel;
    private StudentTrackInfo studentTrackInfo;
    public static final Student dao = new Student();
    public static final String SEARCH_FROM_STUDENT = "select * from stumanager_student ";
    public static final String SQL_FROM = " from stumanager_student ";
    private Status statu;
    @Override
    public boolean equals(Object o) {
        return o instanceof Student && Objects.equals(getId(), ((Student) o).getId());
    }

    public Class getClassModel() {
        return classModel;
    }

    public void setClassModel(Class classModel) {
        this.classModel = classModel;
    }

    public StudentEmployment getStudentEmployment() {
        return studentEmployment;
    }

    public void setStudentEmployment(StudentEmployment studentEmployment) {
        this.studentEmployment = studentEmployment;
    }

    public Status getStatu() {
        return statu;
    }

    public void setStatu(Status statu) {
        this.statu = statu;
    }

    public StudentTrackInfo getStudentTrackInfo() {
        return studentTrackInfo;
    }

    public void setStudentTrackInfo(StudentTrackInfo studentTrackInfo) {
        this.studentTrackInfo = studentTrackInfo;
    }
}
