package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseStudentEmployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentEmployment extends BaseStudentEmployment<StudentEmployment> {
	public static final StudentEmployment dao = new StudentEmployment();
}
