package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseStudentTrackInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentTrackInfo extends BaseStudentTrackInfo<StudentTrackInfo> {
	public static final StudentTrackInfo dao = new StudentTrackInfo();
}
