package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseStudentTrackInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentTrackInfo extends BaseStudentTrackInfo<StudentTrackInfo> {
	public static final StudentTrackInfo dao = new StudentTrackInfo();
	public static final String SELECT_FROM_STUDENT_TRACK_INFO="select * from stumanager_student_track_info ";
	public static final String SQL_FROM=" from stumanager_student_track_info ";
}