package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseSubsidyHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubsidyHistory extends BaseSubsidyHistory<SubsidyHistory> {
	public static final SubsidyHistory dao = new SubsidyHistory();
	public static final String SEARCH_FROM_SUBSIDY_HISTORY = "select * from stumanager_subsidy_history ";

}
