package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseSubsidyApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubsidyApplication extends BaseSubsidyApplication<SubsidyApplication> {
	public static final SubsidyApplication dao = new SubsidyApplication();
}
