package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseSubsidyApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubsidyApplication extends BaseSubsidyApplication<SubsidyApplication> {
	public static final SubsidyApplication dao = new SubsidyApplication();
	public static final String SEARCH_FROM_SUBSIDY_APPLICATION = "select * from stumanager_subsidy_application ";
	public static final String SQL_FROM = " from stumanager_subsidy_application ";
}
