package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseSubsidyHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubsidyHistory extends BaseSubsidyHistory<SubsidyHistory> {
	public static final SubsidyHistory dao = new SubsidyHistory();
}
