package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseSubsidyApplicationSum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubsidyApplicationSum extends BaseSubsidyApplicationSum<SubsidyApplicationSum> {
	public static final SubsidyApplicationSum dao = new SubsidyApplicationSum();
}
