package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestionCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestionCopy extends BaseTestQuestionCopy<TestQuestionCopy> {
	public static final TestQuestionCopy dao = new TestQuestionCopy();
}
