package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestReply extends BaseTestReply<TestReply> {
	public static final TestReply dao = new TestReply();
	public static final String SEARCH_FROM_TEST_REPLY = "select * from stumanager_test_reply ";
}
