package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestionnaireQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestionnaireQuestion extends BaseTestQuestionnaireQuestion<TestQuestionnaireQuestion> {
	public static final TestQuestionnaireQuestion dao = new TestQuestionnaireQuestion();
	public static final String SEARCH_FROM_MODEL = "select * from stumanager_test_questionnaire_question ";
}
