package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTrainingProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainingProject extends BaseTrainingProject<TrainingProject> {
	public static final TrainingProject dao = new TrainingProject();
}
