package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseUserRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRegion extends BaseUserRegion<UserRegion> {
	public static final UserRegion dao = new UserRegion();
	public static final String SELECT_FROM_USERREGION="select * from stumanager_user_region ";

}
