package com.hudongwx.testing.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("testing_t_grade", "id", TGrade.class);
		arp.addMapping("testing_t_question_big_type", "id", TQuestionBigType.class);
		arp.addMapping("testing_t_questionnaire", "id", TQuestionnaire.class);
		arp.addMapping("testing_t_questionnaire_result", "id", TQuestionnaireResult.class);
		arp.addMapping("testing_t_questions", "id", TQuestions.class);
		arp.addMapping("testing_t_questions_questionnaire", "id", TQuestionsQuestionnaire.class);
		arp.addMapping("testing_t_questions_tag", "id", TQuestionsTag.class);
	}
}

