package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseQuestionsQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionsQuestionnaire extends BaseQuestionsQuestionnaire<QuestionsQuestionnaire> {
	public static final QuestionsQuestionnaire dao = new QuestionsQuestionnaire();
}
