package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TGrade extends BaseTGrade<TGrade> {
	public static final TGrade dao = new TGrade();
}
