package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestionnaireResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionnaireResult extends BaseTQuestionnaireResult<TQuestionnaireResult> {
	public static final TQuestionnaireResult dao = new TQuestionnaireResult();
}
