package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestions extends BaseTQuestions<TQuestions> {
	public static final TQuestions dao = new TQuestions();
}
