package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestionsTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionsTag extends BaseTQuestionsTag<TQuestionsTag> {
	public static final TQuestionsTag dao = new TQuestionsTag();
}
