package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestionsQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionsQuestionnaire extends BaseTQuestionsQuestionnaire<TQuestionsQuestionnaire> {
	public static final TQuestionsQuestionnaire dao = new TQuestionsQuestionnaire();
}
