package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestionBigType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionBigType extends BaseTQuestionBigType<TQuestionBigType> {
	public static final TQuestionBigType dao = new TQuestionBigType();
}
