package com.hudongwx.testing.model;

import com.hudongwx.testing.common.BaseTQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionnaire extends BaseTQuestionnaire<TQuestionnaire> {
	public static final TQuestionnaire dao = new TQuestionnaire();
}
