package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questionnaire extends BaseQuestionnaire<Questionnaire> {
	public static final Questionnaire dao = new Questionnaire();
}
