package com.hudongwx.surveys.model;

import com.hudongwx.studentsys.util.Common;
import com.hudongwx.surveys.common.BaseQuestions;
import com.hudongwx.surveys.service.QuestionsNode;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questions extends BaseQuestions<Questions> {
    public static final Questions dao = new Questions();
    private List<QuestionsNode> questionsNodes = new ArrayList<>();
    public List<QuestionsNode> getQuestionsNodes() {
        return questionsNodes;
    }

    public void generateSelects() {
        /*setContent(getContent().replace("&&^&&","&"));
        setOptionScore(getOptionScore().replace("&&^&&","&"));
        update();*/
        String[] sContent = getContent().split(Common.SEPARATOR);
        String[] ssScores = getOptionScore().split(Common.SEPARATOR);
        for(int i = 0; i < sContent.length; i++){
            QuestionsNode q = new QuestionsNode();
            q.setScore(ssScores[i]);
            q.setSelect(sContent[i]);
            questionsNodes.add(q);
        }
    }

}
