package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestionnaireResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionnaireResult extends BaseQuestionnaireResult<QuestionnaireResult> {
	public static final QuestionnaireResult dao = new QuestionnaireResult();
}
