package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questions extends BaseQuestions<Questions> {
	public static final Questions dao = new Questions();
}
