package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestionnaireResult;
import com.hudongwx.surveys.service.Node;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionnaireResult extends BaseQuestionnaireResult<QuestionnaireResult> {
	public static final QuestionnaireResult dao = new QuestionnaireResult();
	public static final String SEARCH_FROM_QUESTIONNAIRE_RESULT = "select * from surveys_t_questionnaire_result ";
	private Node user ;
	private int count;
	public Node getUser() {
		return user;
	}

	public void setUser(Node user) {
		this.user = user;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
}
