package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestionBigType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionBigType extends BaseQuestionBigType<QuestionBigType> {
	public static final QuestionBigType dao = new QuestionBigType();
}
