package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestReply<M extends BaseTestReply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTestQuestionnaireClassId(java.lang.Integer testQuestionnaireClassId) {
		set("testQuestionnaireClassId", testQuestionnaireClassId);
	}

	public java.lang.Integer getTestQuestionnaireClassId() {
		return get("testQuestionnaireClassId");
	}

	public void setAnswers(java.lang.String answers) {
		set("answers", answers);
	}

	public java.lang.String getAnswers() {
		return get("answers");
	}

	public void setStudentId(java.lang.Integer studentId) {
		set("studentId", studentId);
	}

	public java.lang.Integer getStudentId() {
		return get("studentId");
	}

	public void setCorrecting(java.lang.Integer correcting) {
		set("correcting", correcting);
	}

	public java.lang.Integer getCorrecting() {
		return get("correcting");
	}

	public void setScoreSituation(java.lang.String scoreSituation) {
		set("scoreSituation", scoreSituation);
	}

	public java.lang.String getScoreSituation() {
		return get("scoreSituation");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

}
