package com.hudongwx.studentSys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setClassId(java.lang.Long classId) {
		set("classId", classId);
	}

	public java.lang.Long getClassId() {
		return get("classId");
	}

	public void setTutorId(java.lang.Long tutorId) {
		set("tutorId", tutorId);
	}

	public java.lang.Long getTutorId() {
		return get("tutorId");
	}

	public void setSubject(java.lang.Long subject) {
		set("subject", subject);
	}

	public java.lang.Long getSubject() {
		return get("subject");
	}

	public void setContactInformation(java.lang.String contactInformation) {
		set("contactInformation", contactInformation);
	}

	public java.lang.String getContactInformation() {
		return get("contactInformation");
	}

	public void setAdmission(java.util.Date admission) {
		set("admission", admission);
	}

	public java.util.Date getAdmission() {
		return get("admission");
	}

	public void setCredit(java.lang.Integer credit) {
		set("credit", credit);
	}

	public java.lang.Integer getCredit() {
		return get("credit");
	}

	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}

	public java.lang.Integer getGrade() {
		return get("grade");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setEmployment(java.lang.String employment) {
		set("employment", employment);
	}

	public java.lang.String getEmployment() {
		return get("employment");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}

	public java.lang.Long getCreateTime() {
		return get("createTime");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setOpraterId(java.lang.Long opraterId) {
		set("opraterId", opraterId);
	}

	public java.lang.Long getOpraterId() {
		return get("opraterId");
	}

	public void setConsultantId(java.lang.Long consultantId) {
		set("consultantId", consultantId);
	}

	public java.lang.Long getConsultantId() {
		return get("consultantId");
	}

}
