package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestQuestionnaireQuestion<M extends BaseTestQuestionnaireQuestion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTestQuestionnaireId(java.lang.Integer testQuestionnaireId) {
		set("testQuestionnaireId", testQuestionnaireId);
	}

	public java.lang.Integer getTestQuestionnaireId() {
		return get("testQuestionnaireId");
	}

	public void setTestQuestionId(java.lang.Integer testQuestionId) {
		set("testQuestionId", testQuestionId);
	}

	public java.lang.Integer getTestQuestionId() {
		return get("testQuestionId");
	}

	public void setTestQuestionScore(java.lang.Integer testQuestionScore) {
		set("testQuestionScore", testQuestionScore);
	}

	public java.lang.Integer getTestQuestionScore() {
		return get("testQuestionScore");
	}

}
