package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClassName(java.lang.String className) {
		set("className", className);
	}

	public java.lang.String getClassName() {
		return get("className");
	}

	public void setHeadTeacherid(java.lang.Integer headTeacherid) {
		set("headTeacherid", headTeacherid);
	}

	public java.lang.Integer getHeadTeacherid() {
		return get("headTeacherid");
	}

	public void setAssistant(java.lang.String Assistant) {
		set("Assistant", Assistant);
	}

	public java.lang.String getAssistant() {
		return get("Assistant");
	}

	public void setTutorId(java.lang.Integer tutorId) {
		set("tutorId", tutorId);
	}

	public java.lang.Integer getTutorId() {
		return get("tutorId");
	}

}
