package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestType<M extends BaseTestType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
	}

	public java.lang.String getTypeName() {
		return get("typeName");
	}

	public void setTypeQuestionCnt(java.lang.Integer typeQuestionCnt) {
		set("typeQuestionCnt", typeQuestionCnt);
	}

	public java.lang.Integer getTypeQuestionCnt() {
		return get("typeQuestionCnt");
	}

	public void setTypeCreateTime(java.lang.Integer typeCreateTime) {
		set("typeCreateTime", typeCreateTime);
	}

	public java.lang.Integer getTypeCreateTime() {
		return get("typeCreateTime");
	}

	public void setTypeUpdateTime(java.lang.Integer typeUpdateTime) {
		set("typeUpdateTime", typeUpdateTime);
	}

	public java.lang.Integer getTypeUpdateTime() {
		return get("typeUpdateTime");
	}

}
