package com.hudongwx.studentsys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestQuestionnaire<M extends BaseTestQuestionnaire<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTestQuestionnaireTitle(java.lang.String testQuestionnaireTitle) {
		set("testQuestionnaireTitle", testQuestionnaireTitle);
	}

	public java.lang.String getTestQuestionnaireTitle() {
		return get("testQuestionnaireTitle");
	}

	public void setTestQuestionnaireScore(java.lang.Integer testQuestionnaireScore) {
		set("testQuestionnaireScore", testQuestionnaireScore);
	}

	public java.lang.Integer getTestQuestionnaireScore() {
		return get("testQuestionnaireScore");
	}

	public void setTestQuestionnaireCreateTime(java.lang.Long testQuestionnaireCreateTime) {
		set("testQuestionnaireCreateTime", testQuestionnaireCreateTime);
	}

	public java.lang.Long getTestQuestionnaireCreateTime() {
		return get("testQuestionnaireCreateTime");
	}

	public void setTestQuestionnaireStartTime(java.lang.Integer testQuestionnaireStartTime) {
		set("testQuestionnaireStartTime", testQuestionnaireStartTime);
	}

	public java.lang.Integer getTestQuestionnaireStartTime() {
		return get("testQuestionnaireStartTime");
	}

	public void setTestQuestionnaireEndTime(java.lang.Integer testQuestionnaireEndTime) {
		set("testQuestionnaireEndTime", testQuestionnaireEndTime);
	}

	public java.lang.Integer getTestQuestionnaireEndTime() {
		return get("testQuestionnaireEndTime");
	}

	public void setTestQuestionnaireOperaterId(java.lang.Integer testQuestionnaireOperaterId) {
		set("testQuestionnaireOperaterId", testQuestionnaireOperaterId);
	}

	public java.lang.Integer getTestQuestionnaireOperaterId() {
		return get("testQuestionnaireOperaterId");
	}

	public void setTestQuestionnaireMessage(java.lang.String testQuestionnaireMessage) {
		set("testQuestionnaireMessage", testQuestionnaireMessage);
	}

	public java.lang.String getTestQuestionnaireMessage() {
		return get("testQuestionnaireMessage");
	}

}
