package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Certificate extends BaseCertificate<Certificate> {
	public static final Certificate dao = new Certificate();
	public static final String SEARCH_FROM_CERTIFICATE = "select * from stumanager_certificate ";
	public static final String SQL_FROM = " from stumanager_certificate ";
}
