package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();
}
