package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Employee extends BaseEmployee<Employee> {
	public static final Employee dao = new Employee();
}
