package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseRole;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public List<Mapping> allowMappings = null;
}
