package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseRole;
import com.hudongwx.studentsys.util.ArrayTree;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public static final String SEARCH_FROM_ROLE = "select * from stumanager_role ";
	public ArrayTree<Mapping> allowTree = null;
}
