package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
}
