package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	public static final Student dao = new Student();
}
