package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseStudent;

import java.util.Objects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
    public static final Student dao = new Student();
    public static final String SEARCH_FROM_STUDENT = "select * from stumanager_student ";
    public static final String SQL_FROM = " from stumanager_student ";

    @Override
    public boolean equals(Object o) {
        return o instanceof Student && Objects.equals(getId(), ((Student) o).getId());
    }
}
