package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestion extends BaseTestQuestion<TestQuestion> {
	public static final TestQuestion dao = new TestQuestion();
}
