package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestionnaireClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestionnaireClass extends BaseTestQuestionnaireClass<TestQuestionnaireClass> {
	public static final TestQuestionnaireClass dao = new TestQuestionnaireClass();
	public static final String SEARCH_FROM_TEST_QUESTIONNAIRE_CLASS = "select * from stumanager_test_questionnaire_class";
}
