package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestionnaire extends BaseTestQuestionnaire<TestQuestionnaire> {
	public static final TestQuestionnaire dao = new TestQuestionnaire();
	public static final String SEARCH_FROM_TEST_QUESTIONNAIRE = "select * from stumanager_test_questionnaire ";
}
