package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestTag extends BaseTestTag<TestTag> {
	public static final TestTag dao = new TestTag();
}
