package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestQuestionnaireQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestQuestionnaireQuestion extends BaseTestQuestionnaireQuestion<TestQuestionnaireQuestion> {
	public static final TestQuestionnaireQuestion dao = new TestQuestionnaireQuestion();
}
