package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseTestTagQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestTagQuestion extends BaseTestTagQuestion<TestTagQuestion> {
	public static final TestTagQuestion dao = new TestTagQuestion();
}
