package com.hudongwx.studentsys.model;

import com.hudongwx.studentsys.common.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public User getByAccount(){

		return null;
	}
}
