package com.hudongwx.studentSys.model;

import com.hudongwx.studentSys.common.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
