package com.hudongwx.surveys.common;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionBigType<M extends BaseQuestionBigType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSortFlag(java.lang.Integer sortFlag) {
		set("sort_flag", sortFlag);
	}

	public java.lang.Integer getSortFlag() {
		return get("sort_flag");
	}

}
