package com.hudongwx.surveys.model;

import com.hudongwx.surveys.common.BaseQuestionBigType;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionBigType extends BaseQuestionBigType<QuestionBigType> {
	public static final QuestionBigType dao = new QuestionBigType();
	private List<Questions> questionsList = new ArrayList<>();

	public List<Questions> getQuestionsList() {
		return questionsList;
	}
	public void addQuestion(Questions questions){
		questionsList.add(questions);
	}

	public void setQuestionsList(List<Questions> questionsList) {
		this.questionsList = questionsList;
	}
}
